[package]
name = "marco-crate-example"
version = "0.1.0"
edition = "2021"
description = "test for release-plz"
repository = "https://github.com/MarcoIeni/marco-crate-example"
license = "MIT OR Apache-2.0"

[dependencies]
